### ISSUE TITLE
Are ES_HOSTS name resolution and ES_NODES_WAN_ONLY related?

### ISSUE THREAD

**Issue by rdalverny** [apache/incubator-zipkin-dependencies#121]
Hi!

While upgrading from an old 2.2 version to 2.11 (moving from `ES_AWS_DOMAIN` to `ES_HOSTS`), I'm encountering a situation where this will fail (failure to resolve `es-proxy`, although it's present in `/etc/hosts`):

```shell
# this will fail with
#
# org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException:
#   Connection error (check network and/or proxy settings)- all nodes failed;
#   tried [[es-proxy:9200]]
#
STORAGE_TYPE=elasticsearch ES_HOSTS=es-proxy:9200 ES_NODES_WAN_ONLY=true java -jar ...

# this will work:
STORAGE_TYPE=elasticsearch ES_HOSTS=es-proxy:9200 java -jar ...

# this will work (manually resolved IP):
STORAGE_TYPE=elasticsearch ES_HOSTS=10.0.0.1:9200 ES_NODES_WAN_ONLY=true java -jar ...
```

I'm afraid I'm a bit confused. I found that https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html states:

> **es.nodes.wan.only** (default false)
> Whether the connector is used against an Elasticsearch instance in a cloud/restricted environment over the WAN, such as Amazon Web Services. In this mode, the connector disables discovery and only connects through the declared es.nodes during all operations, including reads and writes. Note that in this mode, performance is highly affected.
>
> **es.nodes.resolve.hostname** (default depends)
> Whether the connector should resolve the nodes hostnames to IP addresses or not. By default it is true unless wan mode is enabled (see above) in which case it will default to false.

Does that mean that `ES_NODES_WAN_ONLY` will also skip name resolution? If that's expected, that could make a good explicit mention in the README. Or is that an option somehow that could be added through also setting an `es.nodes.resolve.hostname` equivalent?

**Comment by adriancole** [comment]
we use elasticsearch-hadoop client sometime they change things. can you look at their support channel?
