### ISSUE TITLE
elasticsearch-spark-20_2.11 6.4+ breaks on Elasticsearch 2.x

### ISSUE THREAD

**Issue by adriancole** [apache/incubator-zipkin-dependencies#124]
We are pinned to 6.3.2 as the driver version 6.4+ breaks on Elasticsearch 2.x

cc @openzipkin/elasticsearch

**Comment by adriancole** [comment]
hmm it actually looks like 2.x is supposed to be supported cc @making https://github.com/elastic/elasticsearch-hadoop

**Comment by adriancole** [comment]
just checked and found 7.0.0 driver is worse as it also breaks 5.x (so breaks 2.x and 5.x, logs a bunch of junk on 6.x, but 6.x works)

**Comment by jcarres-mdsol** [comment]
Consider dropping support for ES 2.x?

**Comment by adriancole** [comment]
this discussion is on another thread about the version matrix. if we drop
support people will not upgrade and we have too many half complete things I
dont want people to be pinned on.

ES supports 2.x on their readme it is just broke. until they officially
drop I dont want to break it especially considering how few people asked
for 7 (1) and how unknown amount of people still use 2.x.

**Comment by adriancole** [comment]
here's the break on 5.x which we might be able to work around. https://github.com/elastic/elasticsearch-hadoop/issues/1276

**Comment by adriancole** [comment]
here's the bug regarding ES 2.x https://github.com/elastic/elasticsearch-hadoop/issues/1277
